### ISSUE TITLE
Log what scrubber is doing

### ISSUE THREAD

**Issue by GitRon** [RegioHelden/django-scrubber#18]
Currently scrubber is only logging output from faker, it seems.

```
INFO 2019-11-19 15:27:32,407 scrubbers 22188 20920 Initializing fake scrub data for provider building_number(, )
INFO 2019-11-19 15:27:33,084 scrubbers 22188 20920 Initializing fake scrub data for provider name_female(, )
```

I think it would be awesome if we'd log the current model being scrubbed and maybe - if possible - the amount of records left/handled/processed.

Best  
Ronny

**Comment by costela** [comment]
Hi @GitRon ,

We [already log the model being scrubbed](https://github.com/RegioHelden/django-scrubber/blob/93d03335d1701339bc7e45d8f299a78d818e4202/django_scrubber/management/commands/scrub_data.py#L74).  
Your log settings in https://github.com/RegioHelden/django-scrubber/issues/13#issuecomment-555524355 mean logs from `django_scrubber.management.commands.scrub_data` get ignored. As I mentioned in the other issue, you should probably use `django_scrubber.*` (i.e.: explicitly use the asterisk `*`).

As for your second point: it would be nice, yes, but I'm not sure it's feasible if we want to keep the performance. The current code is fast even for big DBs because the whole scrubbing happens on the DB side. So we basically just send a single SQL `UPDATE` query per model and wait for it to return.  
We could break up the query in batches, but I don't think that's worth the trouble (we'd need transaction handling; keeping track of the batch; new failure scenarios; etc).

I'm open for suggestions though! Maybe I just overlooked some feasible solution.
I'll close this for now, but feel free to add any ideas and I'll reopen it!

**Comment by GitRon** [comment]
Ok, the wildcard is wrong:

```
LOGGING['loggers']['django_scrubber']
```

is working. I update my PR.
