### ISSUE TITLE
How to null a given field

### ISSUE THREAD

**Issue by GitRon** [RegioHelden/django-scrubber#19]
Hi @costela 

I was wondering... how can I null a given field? I looked at faker but there as well not information about what to do.

Any ideas about that?

Thx!  
Ronny

**Comment by costela** [comment]
Hi @GitRon 

any [`Func`](https://docs.djangoproject.com/en/2.2/ref/models/expressions/#func-expressions) will do, so you can just use something like:

```python
from django.db.models import Func

class Null(Func):
    arity = 0
    template = 'NULL'
```

I originally didn't expect this to be a common scenario (because we wanted our scrubbed data to actually have some content), but it's straightforward enough that it should probably be included in the module.

I'll take a look at this later.

**Comment by GitRon** [comment]
Awesome! Thanks! I think it is a nice improvement. My use-case: I have a rarely used memo text field. Adding lorem ipsum there blows up the database by several hundred megabytes. Just empty it is way more convenient.

**Comment by costela** [comment]
@GitRon if you can, please give the PR above a spin.

**Comment by GitRon** [comment]
@costela Awesome! Looks great! Can't wait to get a new release! Will solve 90% of my current issues with scrubbing my data. 👍
